### ISSUE TITLE
Cluster Section

### ISSUE THREAD

**Issue by sdwestwood** [sdwestwood/PISA#3]
- [x] Create .RData file
- [x] Adjust set-up chunk to only include required libraries
- [x] Add commented installation commands for learnr & gradethis
- [x] Add in shiny PCA/Cluster app to final section (Sean)
- [x] Convert to progressive tutorial format (see PCA section)
- [x] Adjust header spacing where necessary for progressive reveal
- [x] Make exercises/feedback consistent with PCA
- [x] Adjust graph colours for consistency if required (Sean)

**Comment by AmyKateRodger** [comment]
Ran the Clusters document and it is too big to open in the editor! 10.1MB

**Comment by AmyKateRodger** [comment]
> Ran the Clusters document and it is too big to open in the editor! 10.1MB

A possible solution could be to move the combining clustering and PCA section to a different rmd file?

**Comment by sdwestwood** [comment]
Might be a good solution^, especially since there is another shiny component to add from my old section

**Comment by AmyKateRodger** [comment]
> Might be a good solution^, especially since there is another shiny component to add from my old section

I've split it up but there's a caveat! The combining PCA and cluster section on its own is 9.9 MB!! I think it might be all the plotly versions of the maps that are hiking up the file size so we might have to do away with some of this section. 

If you add in your shiny app and it goes over 10MB I think we can: (1) either remove the Hierarchical section or (2) remove both the Hierarchical and DBSCAN. In Elliots analysis I think he uses kmeans or DBSCAN, so would make sense to remove Hierarchical or just have one method to illustrate the point rather than all three!
